version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: caixafacil
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: ./apps/api
    ports:
      - "3333:3333"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://admin:secret@postgres:5432/caixafacil

  web:
    build: ./apps/web
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  pgdata:
